EXP_DIR: Dense2p
DEBUG_ALL: False
ALL_TEST: False
ALL_TEST_NUM_TRAIN: 100
ALL_TEST_NUM_VAL: 100
ALL_TEST_NUM_TEST: 1000
EMBED_DIM: 512
CONTEXT_FUSION: False
INIT_BY_GLOVE: False
KEEP_AS_GLOVE_DIM: False
GLOVE_DIM: 300
TRAIN:
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  SUMMARY_INTERVAL: 10
  RPN_BATCHSIZE: 256
  BATCH_SIZE: 256
  PROPOSAL_METHOD: gt
  # BG_THRESH_LO: 0.0
  # FG_FRACTION: 0.5
  RPN_NMS_THRESH: 0.7
  RPN_POST_NMS_TOP_N: 50
  MAX_SIZE: 720
  USE_FLIPPED: True
  LR_DIY_DECAY: False
  STEPSIZE: [1000000]
  # WEIGHT_INITIALIZER: normal
  DISPLAY: 10
  EXP_DECAY_RATE: 0.8
  EXP_DECAY_STEPS: 10000
  OPTIMIZER: 'adam'
  DOUBLE_BIAS: False
  ASPECT_GROUPING: False
RESNET:
  FIXED_BLOCKS: 3
TEST:
  HAS_RPN: True
  RPN_NMS_THRESH: 0.6
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 50
  MAX_SIZE: 720
