import sys
from flask import abort
from flask_restplus import Namespace, Resource, fields
from werkzeug.datastructures import FileStorage

from config import *

sys.path.append('../')
from im2txt.server import ModelWrapper

api = Namespace('model', description='')



label_prediction = api.model('LabelPrediction', {
    'index': fields.String(required=False, description='Labels ranked by highest score'),
    'caption': fields.String(required=True, description='Caption generated by image'),
    'probability': fields.Float(required=True)
})

predict_response = api.model('ModelPredictResponse', {
    'status': fields.String(required=True, description='Response status message'),
    'predictions': fields.List(fields.Nested(label_prediction), description='Predicted labels and probabilities')
})

# set up parser for image input data
image_parser = api.parser()
image_parser.add_argument('image', type=FileStorage, location='files', required=True)

@api.route('/predict')
class Predict(Resource):

    model_wrapper = ModelWrapper()

    @api.doc('predict')
    @api.expect(image_parser)
    @api.marshal_with(predict_response)
    def post(self):
        '''Make a prediction given input data'''
        result = {'status': 'error'}

        args = image_parser.parse_args()

        if not args['image'].mimetype.endswith(('jpg', 'jpeg', 'png')):
            abort(400, 'Invalid file type/extension. Please provide an image in JPEG or PNG format.')

        image_data = args['image'].read()
        preds = self.model_wrapper.predict(image_data)

        label_preds = [{'index': p[0], 'caption': p[1], 'probability': p[2]} for p in [x for x in preds]]
        result['predictions'] = label_preds
        result['status'] = 'ok'

        return result
